### ISSUE TITLE
Missing assert in test_base.py

### ISSUE THREAD

**Issue by Sjord** [gitpython-developers/gitdb#101]
[gitdb/gitdb/test/test\_base.py at master · gitpython-developers/gitdb](https://github.com/gitpython-developers/gitdb/blob/master/gitdb/test/test_base.py#L95)

```
istream.size = s * 2
istream.size == s * 2
```

`istream.size == s * 2` doesn't do anything. It should probably be `assert istream.size == s * 2`.

**Comment by Byron** [comment]
Thanks! Please feel free to submit a PR as well.
