### ISSUE TITLE
Was this intentional?

### ISSUE THREAD

**Issue by pelson** [gitpython-developers/gitdb#24]
requirements.txt references itself: https://github.com/gitpython-developers/gitdb/blob/master/requirements.txt#L1

Just noticed it when building a recipe for conda. Happy for this to be closed immediately.

**Comment by Byron** [comment]
Thanks for letting me know - it was fixed with [this commit](https://github.com/gitpython-developers/gitdb/commit/490fdc2f27ca91898f09defdf20e1237a5ac12aa).
