### ISSUE TITLE
python setup.py bdist_rpm failed if executed from a source distribution of gitdb

### ISSUE THREAD

**Issue by Benoit-DunandLaisin** [gitpython-developers/gitdb#25]
Hi,

Using the gitdb-0.6.4.tar.gz and then:
```
tar -xvf gitdb-0.6.4.tar.gz
cd gitdb-0.6.4
python setup.py bdist_rpm
```
The last command failed:

> RPM build errors:
>     File not found: /xxx/gitdb-0.6.4/build/bdist.linux-x86_64/rpm/BUILDROOT/gitdb-0.6.4-1.x86_64/usr/local/lib/python2.7/dist-packages/gitdb/_perf.so
> error: command 'rpmbuild' failed with exit status 1
> 

Same command from a git clone works.
The problem is that MANIFEST.in is not included in source distribution.
To correct it, please include MANIFEST.in in MANIFEST.in file.

Regards.

Here is my patch:
```
diff --git a/MANIFEST.in b/MANIFEST.in
index 597944f..b939b5d 100644
--- a/MANIFEST.in
+++ b/MANIFEST.in
@@ -3,6 +3,7 @@ include LICENSE
 include CHANGES
 include AUTHORS
 include README
+include MANIFEST.in
 
 include gitdb/_fun.c
 include gitdb/_delta_apply.c
```

**Comment by Byron** [comment]
Sorry for the late reply, and thanks for letting me know.
The edit was made a moment ago, and hopefully fixes the problem described here.
If not, please let me know.
