### ISSUE TITLE
0.6.4 does not build with clang

### ISSUE THREAD

**Issue by 0-wiz-0** [gitpython-developers/gitdb#40]
I see that 2.0.2 is out, but it's a separate project on pypi and 0.6.4 is the last release of the previous project.

When compiling 0.6.4 with clang, I get errors because init_per does not return a value. In my copy of `${PREFIX}/include/python3.6/pyport.h`, `PyMODINIT_FUNC` is defined as `PyObject*`.

The attached patch fixes the problem for me.
[patch-gitdb___fun.c.txt](https://github.com/gitpython-developers/gitdb/files/1127345/patch-gitdb___fun.c.txt)

**Comment by Byron** [comment]
Thanks for the patch. However, 0.6.4 is not supported anymore, and in the latest releases, there is no C version anymore.
Also I lost access to the 0  line of this project, so I couldn't release your patch even if I wanted to :/.
