### ISSUE TITLE
What is the latest official release?

### ISSUE THREAD

**Issue by mcepl** [gitpython-developers/gitdb#45]
When looking at https://pypi.org/project/gitdb/ I see that the latest release is 0.6.4, however when looking at https://github.com/gitpython-developers/gitdb/releases I see 2.0.3. What is the proper latest release and/or why is not PyPI page kept updated?

Thank you

**Comment by Byron** [comment]
The difference lies in the name, and the latest version is called ‘gitdb2’.
Reason for this is loss of access to my previous account, the differently
named packages are owned by my new account.
If this answers your question, please close the issue.

**Comment by mcepl** [comment]
OK, so if I maintain package for openSUSE (I do), I should just continue to package gitdb2 and pretend nothing else changed?

**Comment by Byron** [comment]
I think that would be a viable course. Even though it could be preferable
to gain the insight needed to not have to pretend.
Thanks for your work on open Suse and it’s ecosystem!

**Comment by mcepl** [comment]
> I think that would be a viable course. Even though it could be preferable to gain the insight needed to not have to pretend.

Actually, my experience with PyPI managers is that they are usually very willing to help with any non-standard requests. Take a look at https://pypi.org/help/#feedback and try to contact with plea for help.
