### ISSUE TITLE
PyPi missing releases after 0.6.4?

### ISSUE THREAD

**Issue by darkvertex** [gitpython-developers/gitdb#47]
Is there a reason why on PyPi the latest release is 0.6.4 from 2015: https://pypi.org/project/gitdb/#history
yet https://github.com/gitpython-developers/gitdb/releases goes to 2.0.5?

**Comment by Byron** [comment]
Due to my previous account becoming inaccessible, it was easiest to just create a new package, under a new name.
[Here](https://pypi.org/project/gitdb2/) where you will find the latest releases.
