### ISSUE TITLE
array.tostring and fromstring were removed in Python 3.9

### ISSUE THREAD

**Issue by tirkarthi** [gitpython-developers/gitdb#54]
https://github.com/gitpython-developers/gitdb/blob/43e16318e9ab95f146e230afe0a7cbdc848473fe/gitdb/test/lib.py#L160

https://github.com/gitpython-developers/gitdb/blob/43e16318e9ab95f146e230afe0a7cbdc848473fe/gitdb/pack.py#L413

Ref: https://github.com/python/cpython/pull/17487

**Comment by Byron** [comment]
Thanks for letting us know! 

Would it be feasible for you to submit a PR with these changes? I would presume it to be easily merged.

**Comment by tirkarthi** [comment]
I will submit a PR.

**Comment by Harmon758** [comment]
There already is a PR, #53, that resolves this issue.
