### ISSUE TITLE
3.0.0: signature key-id 763629FEC8788FC35128B5F6EE029D1E5EB40300 not found

### ISSUE THREAD

**Issue by dvzrv** [gitpython-developers/gitdb#55]
For the same reasons I can not build and package [gitpython](https://github.com/gitpython-developers/GitPython/issues/980) for Arch Linux, I can not build and package gitdb in version 3.0.0.

Please fix the trust chain for the new key or release a new version with the already trusted key.

**Comment by Byron** [comment]
Thanks for the reminder - please refer to the linked issue for the anticipated course of action.

**Comment by Byron** [comment]
@dvzrv I have just released v4.0.4 which should be signed with the known key. CC @Harmon758 

In May we should be able to move package signing to CI while maintaining a chain of trust.

**Comment by dvzrv** [comment]
@Byron thanks for being on top of this! :)

I have one follow up question: Why is the package now again pushed to gitdb and not as before gitdb2?

**Comment by Byron** [comment]
Please don't mind the above, I used the wrong signing key.

The way I understand it, `gitdb2` is just for use by older GitPython releases, where is `gitdb` is the package we use from here on. The reason for `gitdb2` to come into existence in the first place was me losing access to my pypi account when they disabled support for Google as login mechanism.

It's a great reminder though, as probably I should also re-release `gitdb2` with the correct signing key for it to be picked up one last time.

**Comment by Byron** [comment]
Release 4.0.5 was created and signed with 2CF6E0B51AAF73F09B1C21174D1DA68C88710E60.
Please feel free to close this issue when verified to be correct.

**Comment by dvzrv** [comment]
4.0.6 is now also signed with `27C50E7F590947D7273A741E85194C08421980C9`.

**Comment by Byron** [comment]
Thank you @dvzrv for staying on top of this, it's much appreciated.
