### ISSUE TITLE
Dependency not updated for smmap in install_requires

### ISSUE THREAD

**Issue by phlax** [gitpython-developers/gitdb#69]
Not sure if this is by intention or omission, but the dependency on smmap is updated in requirements.txt but not in `install_requires` of setup.py

https://github.com/gitpython-developers/gitdb/blob/aa7228e8dbdc2ee6b6bc385e8bee21245a10e98d/setup.py#L23

**Comment by Harmon758** [comment]
Ah, I missed this in #68. I'll bump it for a v4.0.7 release.

**Comment by phlax** [comment]
great thanks

**Comment by Harmon758** [comment]
@Byron v4.0.7 (https://github.com/gitpython-developers/gitdb/commit/6b997cd5fd01dd91ecb08d39e5e9736bc1dc9ba5) is ready to be released to fix this.

**Comment by Byron** [comment]
Thanks everyone! [The release](https://pypi.org/project/gitdb/4.0.7/) is now live.
